
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: mysql
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME}:3306/spring_batch
    username: spring-batch-v4
    password: batchv4
#    platform: mysql
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
#    initialize-schema: always
    